### ISSUE TITLE
Can we set the paginationSource default in rxGrid by using AppGrid on the page load.

### ISSUE THREAD

**Issue by rxdotnetdev2** [rxweb/rxweb#322]
### Description
I have been using @rxweb/grid and I can not set the value of paginationSource which comes under Pagination class default on the page load.

Let me know if there is any resolution to that.

**Comment by ajayojha** [comment]
@rxdotnetdev2 please share the stackblitz link and proper use case.

**Comment by rxdotnetdev2** [comment]
First of all thank you for responding quickly @ajayojha .

https://stackblitz.com/edit/angular-ivy-xrrwof?embed=1&file=src/app/hello.component.ts
Above is the stackblitz URL where I have generated proper use case.

Let me know if there is any solution to that

**Comment by ajayojha** [comment]
@rxdotnetdev2 , The issue has been fixed in the new release, please update project package with the version of @rxweb/grid@0.0.2-beta7.

I am closing this ticket as no further action required on this.

**Comment by rxdotnetdev2** [comment]
Thank you @ajayojha for the reponse in a good way.

But It is hard to find that which property has already solved this feature request issue in latest package as you mentioned.
So could you give a name of the property by which I can add this feature in my code?

**Comment by ajayojha** [comment]
The problem was 20 ```option``` is not selected, when you want to show the initial 20 records, just set the ```maxPerPage``` value of 20. It's automatically selected as well as 20 records will be displayed. Any confusion please let me know.

**Comment by rxdotnetdev2** [comment]
Thanks for the such a quick response @ajayojha sir.

In below URL, I have used the same property as you mentioned but it has still not displayed the output means it did not show the 20 "option" in row dropdown.
https://stackblitz.com/edit/angular-ivy-xrrwof?embed=1&file=src/app/hello.component.ts

**Comment by ajayojha** [comment]
@rxdotnetdev2 the package version is not updated, I am not able to fork the provided URL, as you have not provided to access that. I would suggest two things:

* Please update the project package with the latest version of grid and change the ```maxPerPage``` property value as per your need. It will definitely work.
* Please update the package in stackblitz and check the same.

**Comment by rxdotnetdev2** [comment]
Thanks for all the quick replies.

I have done the same steps as you mentioned but still did not come up with the expected output.
Even though after applying the steps it is displaying the last value of the "pagingSource" property array. Below is the URL for having a look into a latest changes as mentioned :-).

https://stackblitz.com/edit/angular-ivy-xrrwof?embed=1&file=src/app/hello.component.ts

**Comment by ajayojha** [comment]
Have you tried this in your local project?

**Comment by ajayojha** [comment]
if possible, then please come on our gitter channel so we can resolve the talk quickly and come to the conclusion.
